FROM anymock-anymock:latest
WORKDIR /app
COPY core/runner/target/*.jar app-core.jar
COPY manager/runner/target/*.jar app-manager.jar
COPY anymock-fe/dist/ /app/dist/
COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh && mkdir -p /app/logs
EXPOSE 8329 8330
ENTRYPOINT ["/app/docker-entrypoint.sh"]
