server {
    listen 80;
    server_name localhost;

    # 前端静态资源
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index index.html;
    }

    # Manager API 代理
    location /anymockweb/ {
        proxy_pass http://anymock:8329/anymockweb/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Core API 代理
    location /anymockcore/ {
        proxy_pass http://anymock:8330/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
